// Global using directives

global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Xml;
global using System.Xml.Linq;
global using JetBrains.Annotations;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Serialization;
global using SSDTLifecycleExtension.Shared.Contracts;
global using SSDTLifecycleExtension.Shared.Contracts.DataAccess;
global using SSDTLifecycleExtension.Shared.Contracts.Enums;
global using SSDTLifecycleExtension.Shared.Contracts.Factories;
global using SSDTLifecycleExtension.Shared.Contracts.Models;
global using SSDTLifecycleExtension.Shared.Contracts.Services;
global using SSDTLifecycleExtension.Shared.Events;
global using SSDTLifecycleExtension.Shared.Models;
global using SSDTLifecycleExtension.Shared.ModelValidations;